import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Uizard Hackernews Reader',
	description: 'Generated by create next app'
}
export interface Story {
	by: string
	descendants: number
	id: number
	kids: number[]
	score: number
	time: number
	title: string
	type: string
	url: string
}

async function fetcher(): Promise<Story[]> {
	const res = await fetch(
		`https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty`
	)
	const data = await res.json()
	return await data.slice(0, 10)
}

async function itemFetcher(item: number): Promise<Story> {
	const res = await fetch(
		`https://hacker-news.firebaseio.com/v0/item/${item}.json?print=pretty`
	)
	return await res.json()
}

export default async function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	const topStoryIds = await fetcher()
	const items = await Promise.all(
		topStoryIds.map(item => itemFetcher(item as any))
	)
	return (
		<html lang='en' className='h-screen'>
			<body className={inter.className}>
				<nav className='w-full text-center bg-yellow-300 py-3'>
					<Link href='/'>Uizard Hackernews Reader</Link>
				</nav>
				<div className='flex'>
					<aside className='flex flex-col max-w-md overflow-auto overflow-y-scroll'>
						{items.map(({ id, title, by, url }) => {
							return (
								<div key={id} className='border p-2'>
									<h1>{title}</h1>
									<div className='flex'>
										<p className='opacity-50'>Posted by {by}</p>
										<form action='/item' className='ml-auto'>
											<button name='search' value={id}>
												Visit website {'>>'}
											</button>
										</form>
									</div>
								</div>
							)
						})}
					</aside>
					{children}
				</div>
				<footer>
					<p className='text-center text-xs py-3'>
						Created with 🖤 by{' '}
						<Link href='https://www.facuperezm.com'>Facundo</Link>
					</p>
				</footer>
			</body>
		</html>
	)
}
